### ISSUE TITLE
Use setTimeout

### ISSUE THREAD

**Issue by krthr** [sjdonado/monocuco#17]
Hi!

I think we could use `setTimeout` to improve the performance in the search process when the data get bigger.

https://github.com/sjdonado/monocuco/blob/dc5a81f4dece44074f89aab9cff19956a4e7e7dd/src/components/Search/Search.jsx#L24

```js
let timeout = null

const onUpdateWord = txt => {
  if (timeout) clearTimeout(timeout)
  timeout = setTimeout(() => {
    // make search
  }, 500);
}
```

We just wait 500ms to make the search and not every single change on the input.

**Comment by sjdonado** [comment]
Cool! Good feature, let me know if need any further information 😎

**Comment by krthr** [comment]
I will take it!
