### ISSUE TITLE
¿ Por dónde podemos comunicarnos ? 

### ISSUE THREAD

**Issue by Rafaell416** [sjdonado/monocuco#24]
Sería genial tener algún medio para comunicarnos entre todos y así tener una mayor claridad de el enfoque que queremos darle al proyecto, se que es un side project y por ahora no es nada serio pero sería interesante poder discutir un poco las ideas que tengamos o resolver dudas entre desarrolladores.

@sjdonado @krthr

**Comment by krthr** [comment]
Slack, puede ser

**Comment by Rafaell416** [comment]
@sjdonado Necesitamos crear un nuevo slack o podemos usar uno existente ? 

Yo tengo acceso al slack de la comunidad de BarranquillaJS, si quieren podemos usarlo creando un canal para esto.

**Comment by krthr** [comment]
Me gusta la idea. Yo ya estoy en BarranquillaJS

**Comment by jbolivard** [comment]
Quién me dice cómo se hace esa vaina? o podríamos ser gente decente y hablar por whatsapp, no creen?

**Comment by pygabo** [comment]
Un canal dedicado, dentro de BarranquillaJs

**Comment by sjdonado** [comment]
Me parece excelente, @Rafaell416 por fa publica el canal en el README 😎

**Comment by Rafaell416** [comment]
https://barranquillajs.slack.com/join/shared_invite/enQtNDI1OTYwOTE2MjQwLTJhYWIzOGJhZDQ3NDljYmMyZjNiMzUwYWM0ZGMwYTliMWRhYmQ2ZjVhODM4MjE2OTg4YTEwYTQzMjAzMzA1Mzc

@sjdonado @krthr @pygabo @jbolivard  Gente, este es el link para que se unan al slack de BarranquillaJS. Los que ya están en el slack pueden entrar al canal de #monocuco
